backend:
  name: git-gateway
  branch: dev
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "content/settings/website/index.md"
        name: "websiteSettings"
        label: "Website Settings"
        fields:
          - { label: "Website Meta Title", name: "title", widget: "string", hint: 'The meta title for the site'}
          - { label: "Website Meta Description", name: "description", widgets: "string", hint: 'The meta description for the site' }
      - file: "content/settings/profile/index.md"
        name: "profileSettings"
        label: "Profile Settings"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - {
              label: "Profile Image",
              name: "personalProfilePhoto",
              widget: "image",
            }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "About", name: "about", widget: "markdown" }
          - {
              label: "Links",
              name: "links",
              widget: "list",
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: href, name: href, widget: string },
                ],
            }

  - name: "indexPageComponents"
    label: "Landing Page"
    files:
      - file: "src/pages/index/personal-profile/index.md"
        name: "personalProfileV1"
        label: "Personal Profile v1"
        fields:
          - { label: "Component Key", name: "componentKey", widget: "hidden", default: "personal-profile-v1"}
          - { label: "Enabled", name: "enabled", widget: "boolean" }
          - { label: "Order", name: "order", widget: "number" }
      - file: "src/pages/landing/resume/index.md"
        name: "resumeV1"
        label: "Resume v1"
        fields:
          - { label: "Component Key", name: "componentKey", widget: "hidden", default: "resume-v1"}
          - { label: "Enabled", name: "enabled", widget: "boolean" }
          - { label: "Order", name: "order", widget: "number" }
          - {
              label: "Work History",
              name: "workHistory",
              widget: "list",
              fields:
                [
                  { label: "Company", name: "company", widget: "string" },
                  {
                    label: "Company Website URL",
                    name: "companyWebsite",
                    widget: "string",
                  },
                  { label: Title, name: title, widget: string },
                  {
                    label: "Employment Start/End",
                    name: "employmentPeriod",
                    widget: string,
                  },
                  {
                    label: Bulletpoints,
                    name: bulletpoints,
                    widget: list,
                    fields:
                      [{label: Bulletpoint, name: bulletpoint, widget: string}],
                  },
                ],
            }

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - { label: "Enabled", name: "enabled", widget: "boolean" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }