backend:
  name: git-gateway
  branch: dev
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "content/settings/index.md"
        name: "website settings"
        label: "Website Settings"
        fields:
          - { label: "Website Title", name: "title", widget: "string" }
          - { label: "Website Description", name: "description", widgets: "string" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Enabled", name: "enabled", widget: "boolean" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "landing page components"
    label: "Landing Page Components"
    files:
      - file: "content/personal_profile/index.md"
        name: "personal profile"
        label: "Personal Profile"
        fields:
          - { label: "Enabled", name: "enabled", widget: "boolean" }
          - { label: "Order", name: "order", widget: "number" }
          - { label: "Name", name: "name", widget: "string" }
          - {
              label: "Profile Image",
              name: "personal profile photo",
              widget: "image",
            }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "About", name: "about", widget: "markdown" }
          - {
              label: "Links",
              name: "links",
              widget: "list",
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: href, name: href, widget: string },
                ],
            }
      - file: "content/resume/index.md"
        name: "resume"
        label: "Resume"
        fields:
          - { label: "Enabled", name: "enabled", widget: "boolean" }
          - { label: "Order", name: "order", widget: "number" }
          - {
              label: "Work History",
              name: "work history",
              widget: "list",
              fields:
                [
                  { label: "Company", name: "company", widget: "string" },
                  {
                    label: "Company Website URL",
                    name: "company website",
                    widget: "string",
                  },
                  { label: Title, name: title, widget: string },
                  {
                    label: "Employment Start/End",
                    name: "employment period",
                    widget: string,
                  },
                  {
                    label: Bulletpoints,
                    name: bulletpoints,
                    widget: list,
                    fields:
                      [label: Bulletpoint, name: bulletpoint, widget: string],
                  },
                ],
            }
